version: '3.8'
services:
  timescaledb:
    image: timescale/timescaledb:latest-pg15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: binance_db 
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U web -d binance_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: on-failure

  app:
    build: .
    image: gotrade-app
    restart: on-failure
    ports:
      - "4000:4000"
    environment:
      DSN: postgres://web:web@timescaledb:5432/binance_db?sslmode=disable
      APCA_API_KEY_ID: apikey
      APCA_API_SECRET_KEY: apisecret
      DB_PASSWORD: password
    depends_on:
      timescaledb:
        condition: service_healthy
